// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3yPsW4r-2zFQn9SBMpF4df69vlt6fq04',
    appId: '1:901082623271:web:bd48d0a3c6e40a63450d02',
    messagingSenderId: '901082623271',
    projectId: 'vandad-flutter-course',
    authDomain: 'vandad-flutter-course.firebaseapp.com',
    storageBucket: 'vandad-flutter-course.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMrkz-dbRnFQIOaOWbcuUh-HVIUegYoFk',
    appId: '1:901082623271:android:1a8459f018b3a129450d02',
    messagingSenderId: '901082623271',
    projectId: 'vandad-flutter-course',
    storageBucket: 'vandad-flutter-course.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGWX1Kzqks5UiUuwdeQlNP1KeyvOJ3BDc',
    appId: '1:901082623271:ios:5800872cae6b91fa450d02',
    messagingSenderId: '901082623271',
    projectId: 'vandad-flutter-course',
    storageBucket: 'vandad-flutter-course.appspot.com',
    iosClientId: '901082623271-ke6k7vbggr4skjfq0pisrvpra6f7qe7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.vandadFlutterCourse',
  );
}
